services:
  # MongoDB Database
  mongo:
    image: mongo:7
    container_name: generative-imagining-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: generative_imagining
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  # FastAPI Backend
  backend:
    build: ./backend
    container_name: generative-imagining-backend
    restart: unless-stopped
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/?authSource=admin
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - IMAGES_PATH=/app/data/images
    volumes:
      - ./data/images:/app/data/images
    ports:
      - "3338:8000"
    depends_on:
      - mongo
    networks:
      - app-network

  # Next.js Frontend
  frontend:
    build: ./frontend
    container_name: generative-imagining-frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=/api
    ports:
      - "3337:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
